form_app/urls.py
from django.conf.urls import url
from form_app import views

# template tagging
app_name = 'form_app'

urlpatterns = [
    url(r'^index',views.index,name = 'index'),
    url(r'^sample/',views.sample,name = 'sample'),
    url(r'^test/',views.test,name = 'test'),
    url(r'^log/',views.form_log,name='form_log'),
    url(r'^sign/',views.form_sign,name='form_sign'),
    url(r'^data/',views.read_data,name='read_data'),
    url(r'^user_logout',views.user_logout,name = 'user_logout'),
    url(r'^user_text/',views.save_text,name = 'user_text'),
    url(r'^success/',views.success_save,name='success_save'),
    url(r'^image/',views.image,name='image'),
]

starter_pro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from form_app import views


urlpatterns = [
    url(r'^form_app/',include('form_app.urls')), 
    url(r'^admin/', admin.site.urls),
    
]

form_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    user = models.OneToOneField(User)
    def __str__(self):
        return (self.user)
    
    def get_data(self,field):
        return  getattr(self,field)

class UserTextData(models.Model):
    user = models.OneToOneField(User,unique = 'TRUE')
    text = models.CharField(max_length=1000)

    def __str__(self):
        return (self.user.username)

    def get_data(self,field):
        return  getattr(self,field)

class UserImageData(models.Model):
    user = models.OneToOneField(User)
    image = models.ImageField(upload_to='saved_pics/')

    def __str__(self):
        return (self.user)


form_app/forms.py
from django import forms
from django.forms import ModelForm
from django.core import validators
from form_app.models import UserInfo,UserTextData,UserImageData
from django.contrib.auth.models import User

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

class TextForm(ModelForm):
    class Meta:
        model = UserTextData
        fields = ['user','text']

class ImageForm(ModelForm):
    class Meta:
        model = UserImageData
        fields = ['user','image']



    

form_app/views.py
from django.shortcuts import render
from form_app.models import UserInfo,UserTextData
from form_app.forms import UserForm,TextForm,ImageForm
from django.core import validators
from django import forms
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout

#-----------------
#    HOME PAGE    
#-----------------

def index(request):
    logout(request)
    return render(request,'form_app/index.html')

#-----------------
#    SIGN-UP PAGE    
#-----------------

def form_sign(request):
    user_form = UserForm()

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            return render(request,'form_app/submit.html',{'status':'success_sign','user':user_form.cleaned_data['username']})
                    
    return render(request,'form_app/form_content.html',{'form':user_form})

#-----------------
#    LOG-IN PAGE    
#-----------------

def form_log(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username,password = password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request,'form_app/submit.html',{'user':username,'status':'success_log'})

            else:
                return HttpResponse("account not active")
        
        else:
            print('login failed')
            print('username: {} and password: {}'.format(username,password))
            return HttpResponse("invalid login details")

    return render(request,'form_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request,'form_app/index.html')

def read_data(request):
    str = ""
    for obj in users.objects.all():
        str += obj.get_data('email') + "<br>"
    return HttpResponse(str)

@login_required
def save_text(request):
    user = request.user
    for obj in UserTextData.objects.all():
        if obj.get_data('user') == user:
            return HttpResponse("text data already saved")
    text = TextForm()
    if request.method=='POST':
        text = TextForm(request.POST)
        if text.is_valid():
            text.save()
            print("text saved successfully")
            return render(request,'form_app/submit_text.html')
        else:
            print(text.errors)
            return HttpResponse("invalid text details")
    
    return render(request,'form_app/text.html',{'text_form':text, })

@login_required
def image(request):
    image = ImageForm(request.POST,request.FILES)
    if request.method== 'POST':
        if image.is_valid():
            image.save()
            print("image saved successfully")

        else:
            return HttpResponse("invalid image")

    return render(request,'form_app/image.html',{'image_form':image})

def sample(request):
    return render(request,'form_app/relative_urls.html')

def test(request):
    return render(request,'form_app/test.html')

def success_save(request):
    return render(request,'form_app/submit_text.html')

templates/form_app/base.html
<html>
    <body>
        {% block start %}
        
        <p>this text is inserted through template inheritance</p>
        
        {% endblock %}
    </body>
</html>

templates/form_app/form_content.html
{% load staticfiles %}
<html>
    <head>
        <title>Form Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    </head>
    <body>
        <div class="jumbotron">
            <form method="post">
                <div>
                    {{form.as_p}}
                </div>
                {% csrf_token %}
                <div>
                    <input type="submit" class = "btn btn-primary" value="Enter">
                    <a href="{% url 'form_app:index' %}" class = "btn btn-primary">Home</a>
                </div>
                
            </form>
            
        </div>
    </body>
</html>

templates/form_app/image.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    </head>
    <body>
        <h2>select the image below and save</h2>
        <form method="POST">
            {% csrf_token %}
            {{ image_form.as_p}}
            <input type="submit" class = "btn btn-primary" value="Save">
        </form>
    </body>
</html>

templates/form_app/index.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    </head>
    <body>
        <div class="jumbotron">
            <h1 style="margin-bottom : 30px">Welcome to My first 'Django' built app</h1>
            <a href="{% url 'form_app:form_sign' %}" class="btn btn-primary">Sign-Up</a>
            <a href="{% url 'form_app:form_log' %}" class="btn btn-primary">Log-In</a>
        </div>
    </body>
</html>

templates/form_app/login.html
<h1>Enter your login credentials</h1>
<form method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type = "text" name="username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" value="Login">
</form>

templates/form_app/relative_urls.html
<html>
    <body>
        <h1>Welcome to relative url templates</h1>
        <a href = {% url 'form_app:test' %}>test file</a>
        <a href = {% url 'admin:index' %}>Admin</a>
    </body>
</html>

templates/form_app/submit.html
<html>
    <head>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    </head>
    <body>
        <div class="jumbotron">
            {% if status == 'success_sign' %}
                <h1 style="margin-bottom : 30px">registered successfully! Welcome {{user}}</h1>
                <a href={% url 'form_app:index' %} class="btn btn-primary">Log Out</a>
                <a href={% url 'form_app:user_text' %} class = "btn btn-secondary">Save text data</a>
                <a href={% url 'form_app:image' %} class = "btn btn-secondary">Save image</a>

            {% elif status == 'repeat_sign' %}
                <h1 style="margin-bottom : 30px">User already registered</h1>
                <a href={% url 'form_app:form_sign' %} class="btn btn-primary">Sign-Up</a>
                <a href={% url 'form_app:form_log' %} class="btn btn-primary">Log In</a>
                <a href={% url 'form_app:index' %} class="btn btn-primary">Home</a>

            {% elif status == 'error_sign' %}
                <h1 style="margin-bottom : 30px">Could not register successfully</h1>
                <a href={% url 'form_app:form_sign' %} class="btn btn-primary">Sign-Up</a>
                <a href={% url 'form_app:form_log' %} class="btn btn-primary">Log In</a>
                <a href={% url 'form_app:index' %} class="btn btn-primary">Home</a>

            {% elif status == 'success_log' %}
                <h1 style="margin-bottom : 30px">Logged In successfully! Welcome {{user}}</h1>
                <a href={% url 'form_app:user_logout' %} class="btn btn-primary">Log Out</a>
                <a href={% url 'form_app:user_text' %} class = "btn btn-secondary">Save text data</a>
                <a href={% url 'form_app:image' %} class = "btn btn-secondary">Save image</a>

            {% elif status == 'fail_log' %}
                <h1 style="margin-bottom : 30px">Could not log in! Either email or password is incorrect</h1>
                <a href={% url 'form_app:form_sign' %} class="btn btn-primary">Sign-Up</a>
                <a href={% url 'form_app:form_log' %} class="btn btn-primary">Log In</a>
                <a href={% url 'form_app:index' %} class="btn btn-primary">Home</a>

            {% elif status == 'error_log' %}
                <h1 style="margin-bottom : 30px">Failed to Log In</h1>
                <a href={% url 'form_app:form_sign' %} class="btn btn-primary">Sign-Up</a>
                <a href={% url 'form_app:form_log' %} class="btn btn-primary">Log In</a>
                <a href={% url 'form_app:index' %} class="btn btn-primary">Home</a>

            {% endif %}
        </div>
        
    </body>
</html>

templates/form_app/submit_text.html
<html>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <h1>Your text has been saved</h1>
    <a href = {% url 'form_app:index'} class="btn btn-primary">LogOut</a>
</html>

templates/form_app/text.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
        <style>
            #text_area{
                border: 2px black solid
            }
        </style>
    </head>
    <body>
        <h2>write the text below and save</h2>
        <form method="POST">
            {% csrf_token %}
            {{ text_form.as_p}}
            <input type="submit" class = "btn btn-primary" value="Save">
        </form>
    </body>
</html>